#!/bin/bash

DIR=~/Dropbox/Notes
EXTENSION=txt

if [[ $# -eq 0 ]]; then
    ls -tr1 $DIR
    exit
fi

FILE=`find $DIR -iname *"${@:1}"* -printf '%T@ %p\n' | sort -k 1nr | sed 's/^[^ ]* //' | head -n 1`

if [[ $FILE = "" ]]; then
    FILE="${@:1}.$EXTENSION"
fi

/usr/bin/editor "$FILE"
